import type {
  Category,
  Glyph,
  Liquidity,
  Pet,
  Tier,
  Variant,
  VariantValue,
} from "./types";

interface Seed {
  id: string;
  name: string;
  aliases: string[];
  cat?: Category;
  tier: Tier;
  liq: Liquidity;
  demand: 1 | 2 | 3 | 4 | 5;
  featured?: boolean;
  frPts: number;
  frUsd: number;
  glyph: Glyph;
  nfrMul?: number;
  mfrMul?: number;
  noVariants?: boolean;
  pts?: Partial<Record<Variant, number>>;
  usd?: Partial<Record<Variant, number>>;
}

const MUL: Record<Variant, number> = {
  regular: 0.86,
  fly: 0.92,
  ride: 0.95,
  fr: 1,
  nfr: 2.45,
  mfr: 6.15,
};

function roundMoney(n: number) {
  if (n >= 100) return Math.round(n);
  if (n >= 20) return Math.round(n * 2) / 2;
  if (n >= 5) return Math.round(n * 10) / 10;
  return Math.round(n * 100) / 100;
}

function roundPts(n: number) {
  if (n >= 50) return Math.round(n);
  if (n >= 10) return Math.round(n * 2) / 2;
  return Math.round(n * 10) / 10;
}

function expand(seed: Seed): Pet {
  const hasVariants = !seed.noVariants && seed.cat !== "potion" && seed.cat !== "egg" && seed.cat !== "item";
  const values = {} as Record<Variant, VariantValue>;
  (Object.keys(MUL) as Variant[]).forEach((variant) => {
    let m = MUL[variant];
    if (variant === "nfr" && seed.nfrMul) m = seed.nfrMul;
    if (variant === "mfr" && seed.mfrMul) m = seed.mfrMul;
    if (!hasVariants) m = 1;
    values[variant] = {
      points: seed.pts?.[variant] ?? roundPts(seed.frPts * m),
      usd: seed.usd?.[variant] ?? roundMoney(seed.frUsd * m),
    };
  });
  return {
    id: seed.id,
    name: seed.name,
    aliases: seed.aliases,
    category: seed.cat ?? "pet",
    tier: seed.tier,
    liquidity: seed.liq,
    demand: seed.demand,
    featured: seed.featured,
    hasVariants,
    glyph: seed.glyph,
    values,
  };
}

const SEEDS: Seed[] = [
  {
    id: "bat-dragon",
    name: "Bat Dragon",
    aliases: ["bat", "morcego", "dragão morcego", "bat drag"],
    tier: "S",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 800,
    frUsd: 413,
    glyph: "void",
    nfrMul: 2.31,
    mfrMul: 5.63,
    usd: { regular: 350, fly: 376, ride: 392, fr: 413, nfr: 900, mfr: 2250 },
    pts: { regular: 688, fly: 736, ride: 760, fr: 800, nfr: 1850, mfr: 4500 },
  },
  {
    id: "shadow-dragon",
    name: "Shadow Dragon",
    aliases: ["shadow", "sombra", "dragão sombra", "sombra drag"],
    tier: "S",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 480,
    frUsd: 294,
    glyph: "night",
    nfrMul: 2.6,
    mfrMul: 5.21,
    usd: { regular: 251, fly: 270, ride: 279, fr: 294, nfr: 625, mfr: 1700 },
    pts: { regular: 413, fly: 442, ride: 456, fr: 480, nfr: 1250, mfr: 2500 },
  },
  {
    id: "giraffe",
    name: "Giraffe",
    aliases: ["girafa", "gira"],
    tier: "S",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 340,
    frUsd: 198,
    glyph: "sun",
    nfrMul: 2.29,
    mfrMul: 7.35,
    usd: { regular: 169, fly: 181, ride: 189, fr: 198, nfr: 390, mfr: 1250 },
    pts: { regular: 292, fly: 313, ride: 323, fr: 340, nfr: 780, mfr: 2500 },
  },
  {
    id: "frost-dragon",
    name: "Frost Dragon",
    aliases: ["frost", "gelo", "dragão de gelo", "frost drag"],
    tier: "S",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 240,
    frUsd: 153,
    glyph: "frost",
    nfrMul: 2.33,
    mfrMul: 6.17,
    usd: { regular: 128, fly: 138, ride: 145, fr: 153, nfr: 280, mfr: 740 },
    pts: { regular: 206, fly: 221, ride: 228, fr: 240, nfr: 560, mfr: 1480 },
  },
  {
    id: "owl",
    name: "Owl",
    aliases: ["coruja", "owl"],
    tier: "S",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 230,
    frUsd: 130,
    glyph: "sand",
    nfrMul: 2.83,
    mfrMul: 9.13,
    usd: { regular: 107, fly: 118, ride: 124, fr: 130, nfr: 325, mfr: 1050 },
    pts: { regular: 198, fly: 212, ride: 218, fr: 230, nfr: 650, mfr: 2100 },
  },
  {
    id: "parrot",
    name: "Parrot",
    aliases: ["papagaio", "parrot"],
    tier: "S",
    liq: "high",
    demand: 4,
    frPts: 170,
    frUsd: 109,
    glyph: "moss",
    nfrMul: 2.18,
    mfrMul: 8.24,
    usd: { regular: 90, fly: 97, ride: 103, fr: 109, nfr: 185, mfr: 700 },
    pts: { regular: 146, fly: 156, ride: 162, fr: 170, nfr: 370, mfr: 1400 },
  },
  {
    id: "crow",
    name: "Crow",
    aliases: ["corvo", "crow"],
    tier: "S",
    liq: "high",
    demand: 4,
    featured: true,
    frPts: 176,
    frUsd: 93,
    glyph: "ink",
    nfrMul: 2.27,
    mfrMul: 7.56,
    usd: { regular: 76, fly: 82, ride: 89, fr: 93, nfr: 200, mfr: 665 },
    pts: { regular: 151, fly: 162, ride: 167, fr: 176, nfr: 400, mfr: 1330 },
  },
  {
    id: "african-wild-dog",
    name: "African Wild Dog",
    aliases: ["awd", "wild dog", "cão selvagem"],
    tier: "A",
    liq: "high",
    demand: 4,
    frPts: 146,
    frUsd: 73,
    glyph: "copper",
    nfrMul: 3.77,
    mfrMul: 9.38,
    usd: { regular: 60, fly: 66, ride: 70, fr: 73, nfr: 275, mfr: 685 },
  },
  {
    id: "balloon-unicorn",
    name: "Balloon Unicorn",
    aliases: ["balloon", "unicórnio balão", "balloon uni"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 210,
    frUsd: 105,
    glyph: "wine",
    nfrMul: 2.62,
    mfrMul: 7.38,
    usd: { regular: 88, fly: 95, ride: 100, fr: 105, nfr: 275, mfr: 775 },
  },
  {
    id: "giant-panda",
    name: "Giant Panda",
    aliases: ["panda gigante", "giant panda"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 140,
    frUsd: 70,
    glyph: "bone",
    nfrMul: 3.29,
    mfrMul: 10.7,
    usd: { regular: 58, fly: 64, ride: 67, fr: 70, nfr: 230, mfr: 750 },
  },
  {
    id: "evil-unicorn",
    name: "Evil Unicorn",
    aliases: ["evil uni", "unicórnio evil", "evil"],
    tier: "A",
    liq: "high",
    demand: 4,
    frPts: 110,
    frUsd: 75,
    glyph: "blood",
    nfrMul: 2.6,
    mfrMul: 6.4,
  },
  {
    id: "arctic-reindeer",
    name: "Arctic Reindeer",
    aliases: ["arctic", "rena", "reindeer", "rena ártica"],
    tier: "A",
    liq: "high",
    demand: 4,
    frPts: 64,
    frUsd: 38,
    glyph: "pearl",
  },
  {
    id: "turtle",
    name: "Turtle",
    aliases: ["tartaruga", "turtle"],
    tier: "A",
    liq: "high",
    demand: 4,
    frPts: 44,
    frUsd: 21,
    glyph: "forest",
  },
  {
    id: "kangaroo",
    name: "Kangaroo",
    aliases: ["canguru", "kanga"],
    tier: "A",
    liq: "high",
    demand: 4,
    frPts: 36,
    frUsd: 17,
    glyph: "copper",
  },
  {
    id: "albino-monkey",
    name: "Albino Monkey",
    aliases: ["albino", "macaco albino"],
    tier: "A",
    liq: "high",
    demand: 3,
    frPts: 32,
    frUsd: 16,
    glyph: "bone",
  },
  {
    id: "hedgehog",
    name: "Hedgehog",
    aliases: ["ouriço", "hedgehog"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 28,
    frUsd: 14,
    glyph: "sand",
  },
  {
    id: "flamingo",
    name: "Flamingo",
    aliases: ["flamingo"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 22,
    frUsd: 11,
    glyph: "wine",
  },
  {
    id: "diamond-butterfly",
    name: "Diamond Butterfly",
    aliases: ["diamond butterfly", "borboleta diamante"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 50,
    frUsd: 25,
    glyph: "frost",
  },
  {
    id: "diamond-ladybug",
    name: "Diamond Ladybug",
    aliases: ["ladybug diamante", "diamond ladybug"],
    tier: "A",
    liq: "medium",
    demand: 3,
    frPts: 40,
    frUsd: 20,
    glyph: "storm",
  },
  {
    id: "lion",
    name: "Lion",
    aliases: ["leão", "lion"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 18,
    frUsd: 9,
    glyph: "sun",
  },
  {
    id: "dalmatian",
    name: "Dalmatian",
    aliases: ["dálmata", "dalmatian"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 16,
    frUsd: 8,
    glyph: "bone",
  },
  {
    id: "queen-bee",
    name: "Queen Bee",
    aliases: ["queen bee", "abelha rainha"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 16,
    frUsd: 8,
    glyph: "sun",
  },
  {
    id: "hawk",
    name: "Hawk",
    aliases: ["falcão", "hawk"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 16,
    frUsd: 8,
    glyph: "steel",
  },
  {
    id: "vampire-dragon",
    name: "Vampire Dragon",
    aliases: ["vampire", "vampiro", "dragão vampiro"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 36,
    frUsd: 18,
    glyph: "blood",
  },
  {
    id: "lavender-dragon",
    name: "Lavender Dragon",
    aliases: ["lavender", "lavanda"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 30,
    frUsd: 15,
    glyph: "wine",
  },
  {
    id: "ghost-dragon",
    name: "Ghost Dragon",
    aliases: ["ghost", "fantasma", "dragão fantasma"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 24,
    frUsd: 12,
    glyph: "pearl",
  },
  {
    id: "ninja-monkey",
    name: "Ninja Monkey",
    aliases: ["ninja", "macaco ninja"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 14,
    frUsd: 7,
    glyph: "ink",
  },
  {
    id: "skele-rex",
    name: "Skele-Rex",
    aliases: ["skelerex", "skele", "esqueleto"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 14,
    frUsd: 7,
    glyph: "bone",
  },
  {
    id: "king-bee",
    name: "King Bee",
    aliases: ["king bee", "abelha rei"],
    tier: "B",
    liq: "medium",
    demand: 2,
    frPts: 12,
    frUsd: 6,
    glyph: "sun",
  },
  {
    id: "phoenix",
    name: "Phoenix",
    aliases: ["fénix", "fenix", "phoenix"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 12,
    frUsd: 6,
    glyph: "ember",
  },
  {
    id: "t-rex",
    name: "T-Rex",
    aliases: ["trex", "t rex", "tiranossauro"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 12,
    frUsd: 6,
    glyph: "moss",
  },
  {
    id: "golden-penguin",
    name: "Golden Penguin",
    aliases: ["pinguim dourado", "golden penguin"],
    tier: "B",
    liq: "medium",
    demand: 2,
    frPts: 12,
    frUsd: 6,
    glyph: "sun",
  },
  {
    id: "dodo",
    name: "Dodo",
    aliases: ["dodo"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 10,
    frUsd: 5,
    glyph: "sand",
  },
  {
    id: "dragon",
    name: "Dragon",
    aliases: ["dragão", "dragao", "legendary dragon"],
    tier: "B",
    liq: "high",
    demand: 4,
    frPts: 10,
    frUsd: 5,
    glyph: "ember",
  },
  {
    id: "frost-fury",
    name: "Frost Fury",
    aliases: ["fury", "frost fury"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 10,
    frUsd: 5,
    glyph: "frost",
  },
  {
    id: "octopus",
    name: "Octopus",
    aliases: ["polvo", "octopus"],
    tier: "B",
    liq: "medium",
    demand: 2,
    frPts: 10,
    frUsd: 5,
    glyph: "ocean",
  },
  {
    id: "unicorn",
    name: "Unicorn",
    aliases: ["unicórnio", "unicornio", "uni"],
    tier: "B",
    liq: "high",
    demand: 4,
    frPts: 9,
    frUsd: 4.5,
    glyph: "pearl",
  },
  {
    id: "griffin",
    name: "Griffin",
    aliases: ["grifo", "griffin"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 8,
    frUsd: 4,
    glyph: "sand",
  },
  {
    id: "shark",
    name: "Shark",
    aliases: ["tubarão", "tubarao", "shark"],
    tier: "B",
    liq: "medium",
    demand: 2,
    frPts: 8,
    frUsd: 4,
    glyph: "steel",
  },
  {
    id: "kitsune",
    name: "Kitsune",
    aliases: ["kitsune"],
    tier: "B",
    liq: "medium",
    demand: 3,
    frPts: 7,
    frUsd: 3.5,
    glyph: "ember",
  },
  {
    id: "cobra",
    name: "Cobra",
    aliases: ["cobra"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 6,
    frUsd: 3,
    glyph: "moss",
  },
  {
    id: "elephant",
    name: "Elephant",
    aliases: ["elefante", "elephant"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 5.5,
    frUsd: 2.8,
    glyph: "steel",
  },
  {
    id: "hyena",
    name: "Hyena",
    aliases: ["hiena", "hyena"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 5,
    frUsd: 2.5,
    glyph: "sand",
  },
  {
    id: "cerberus",
    name: "Cerberus",
    aliases: ["cérbero", "cerberus"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 5,
    frUsd: 2.5,
    glyph: "ember",
  },
  {
    id: "peacock",
    name: "Peacock",
    aliases: ["pavão", "pavao", "peacock"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 4.5,
    frUsd: 2.2,
    glyph: "teal",
  },
  {
    id: "capybara",
    name: "Capybara",
    aliases: ["capivara", "capybara"],
    tier: "C",
    liq: "medium",
    demand: 3,
    frPts: 4.5,
    frUsd: 2.2,
    glyph: "clay",
  },
  {
    id: "axolotl",
    name: "Axolotl",
    aliases: ["axolotl", "axolote"],
    tier: "C",
    liq: "medium",
    demand: 3,
    frPts: 4,
    frUsd: 2,
    glyph: "wine",
  },
  {
    id: "snow-owl",
    name: "Snow Owl",
    aliases: ["snow owl", "coruja da neve"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 4,
    frUsd: 2,
    glyph: "pearl",
  },
  {
    id: "zombie-buffalo",
    name: "Zombie Buffalo",
    aliases: ["zombie buffalo", "búfalo zombie"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 3.5,
    frUsd: 1.8,
    glyph: "moss",
  },
  {
    id: "brown-bear",
    name: "Brown Bear",
    aliases: ["urso", "brown bear"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3.5,
    frUsd: 1.8,
    glyph: "copper",
  },
  {
    id: "polar-bear",
    name: "Polar Bear",
    aliases: ["urso polar", "polar bear"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3.5,
    frUsd: 1.8,
    glyph: "frost",
  },
  {
    id: "swan",
    name: "Swan",
    aliases: ["cisne", "swan"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3.2,
    frUsd: 1.6,
    glyph: "pearl",
  },
  {
    id: "fennec-fox",
    name: "Fennec Fox",
    aliases: ["fennec", "raposa fennec"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3,
    frUsd: 1.5,
    glyph: "sand",
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    aliases: ["shiba", "shiba inu"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3,
    frUsd: 1.5,
    glyph: "copper",
  },
  {
    id: "husky",
    name: "Husky",
    aliases: ["husky"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2.8,
    frUsd: 1.4,
    glyph: "steel",
  },
  {
    id: "crocodile",
    name: "Crocodile",
    aliases: ["crocodilo", "crocodile"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 2.8,
    frUsd: 1.4,
    glyph: "forest",
  },
  {
    id: "red-panda",
    name: "Red Panda",
    aliases: ["red panda", "panda vermelho"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2.6,
    frUsd: 1.3,
    glyph: "ember",
  },
  {
    id: "koala",
    name: "Koala",
    aliases: ["koala"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2.4,
    frUsd: 1.2,
    glyph: "bone",
  },
  {
    id: "panda",
    name: "Panda",
    aliases: ["panda"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2.4,
    frUsd: 1.2,
    glyph: "ink",
  },
  {
    id: "sloth",
    name: "Sloth",
    aliases: ["preguiça", "preguica", "sloth"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 2.2,
    frUsd: 1.1,
    glyph: "clay",
  },
  {
    id: "platypus",
    name: "Platypus",
    aliases: ["ornitorrinco", "platypus"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 2.2,
    frUsd: 1.1,
    glyph: "teal",
  },
  {
    id: "narwhal",
    name: "Narwhal",
    aliases: ["narval", "narwhal"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 2,
    frUsd: 1,
    glyph: "frost",
  },
  {
    id: "dolphin",
    name: "Dolphin",
    aliases: ["golfinho", "dolphin"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2,
    frUsd: 1,
    glyph: "ocean",
  },
  {
    id: "black-panther",
    name: "Black Panther",
    aliases: ["pantera", "black panther"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2,
    frUsd: 1,
    glyph: "void",
  },
  {
    id: "cow",
    name: "Cow",
    aliases: ["vaca", "cow"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 1.8,
    frUsd: 0.9,
    glyph: "bone",
  },
  {
    id: "monkey",
    name: "Monkey",
    aliases: ["macaco", "monkey"],
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 1.6,
    frUsd: 0.8,
    glyph: "copper",
  },
  {
    id: "pig",
    name: "Pig",
    aliases: ["porco", "pig"],
    tier: "C",
    liq: "low",
    demand: 1,
    frPts: 1.4,
    frUsd: 0.7,
    glyph: "wine",
  },
  {
    id: "silly-duck",
    name: "Silly Duck",
    aliases: ["silly duck", "pato"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 1.4,
    frUsd: 0.7,
    glyph: "sun",
  },
  {
    id: "snowman",
    name: "Snowman",
    aliases: ["boneco de neve", "snowman"],
    tier: "C",
    liq: "low",
    demand: 1,
    frPts: 1.2,
    frUsd: 0.6,
    glyph: "pearl",
  },
  {
    id: "ginger-cat",
    name: "Ginger Cat",
    aliases: ["ginger cat", "gato gengibre"],
    tier: "C",
    liq: "low",
    demand: 2,
    frPts: 1.2,
    frUsd: 0.6,
    glyph: "ember",
  },
  {
    id: "squid",
    name: "Squid",
    aliases: ["lula", "squid"],
    tier: "C",
    liq: "low",
    demand: 1,
    frPts: 1.1,
    frUsd: 0.55,
    glyph: "wine",
  },
  {
    id: "chicken",
    name: "Chicken",
    aliases: ["galinha", "chicken"],
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 0.8,
    frUsd: 0.4,
    glyph: "sand",
  },
  {
    id: "cat",
    name: "Cat",
    aliases: ["gato", "cat"],
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 0.4,
    frUsd: 0.2,
    glyph: "steel",
  },
  {
    id: "dog",
    name: "Dog",
    aliases: ["cão", "cao", "dog"],
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 0.4,
    frUsd: 0.2,
    glyph: "copper",
  },
  {
    id: "buffalo",
    name: "Buffalo",
    aliases: ["búfalo", "bufalo", "buffalo"],
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 0.5,
    frUsd: 0.25,
    glyph: "ink",
  },
  {
    id: "bandicoot",
    name: "Bandicoot",
    aliases: ["bandicoot"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.3,
    frUsd: 0.15,
    glyph: "clay",
  },
  {
    id: "robin",
    name: "Robin",
    aliases: ["pisco", "robin"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.25,
    frUsd: 0.12,
    glyph: "ember",
  },
  {
    id: "ground-sloth",
    name: "Ground Sloth",
    aliases: ["ground sloth", "preguiça terrestre"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.6,
    frUsd: 0.3,
    glyph: "clay",
  },
  {
    id: "minion-chick",
    name: "Minion Chick",
    aliases: ["minion", "chick", "pintainho", "minion chick"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.5,
    frUsd: 0.2,
    glyph: "sun",
  },
  {
    id: "metal-ox",
    name: "Metal Ox",
    aliases: ["metal ox", "boi metal", "ox metal"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.8,
    frUsd: 0.35,
    glyph: "steel",
  },
  {
    id: "ox",
    name: "Ox",
    aliases: ["ox", "boi"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.6,
    frUsd: 0.28,
    glyph: "ink",
  },
  {
    id: "crab",
    name: "Crab",
    aliases: ["caranguejo", "crab"],
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.35,
    frUsd: 0.15,
    glyph: "ember",
  },
  {
    id: "stingray",
    name: "Stingray",
    aliases: ["raia", "stingray"],
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 0.9,
    frUsd: 0.45,
    glyph: "ocean",
  },
  {
    id: "ride-potion",
    name: "Ride Potion",
    aliases: ["ride", "rp", "poção ride", "pocao ride", "ride pot"],
    cat: "potion",
    tier: "B",
    liq: "high",
    demand: 5,
    featured: true,
    frPts: 2.5,
    frUsd: 1.2,
    glyph: "teal",
    noVariants: true,
  },
  {
    id: "fly-potion",
    name: "Fly Potion",
    aliases: ["fly", "fp", "poção fly", "pocao fly", "fly pot"],
    cat: "potion",
    tier: "B",
    liq: "high",
    demand: 5,
    frPts: 2.2,
    frUsd: 1,
    glyph: "storm",
    noVariants: true,
  },
  {
    id: "age-up-potion",
    name: "Age-Up Potion",
    aliases: ["age up", "aup", "poção idade"],
    cat: "potion",
    tier: "C",
    liq: "high",
    demand: 4,
    frPts: 0.8,
    frUsd: 0.4,
    glyph: "mint",
    noVariants: true,
  },
  {
    id: "cracked-egg",
    name: "Cracked Egg",
    aliases: ["cracked egg", "ovo rachado"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.1,
    frUsd: 0.05,
    glyph: "bone",
    noVariants: true,
  },
  {
    id: "royal-egg",
    name: "Royal Egg",
    aliases: ["royal egg", "ovo royal", "ovo atual", "current egg"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 1.5,
    frUsd: 0.7,
    glyph: "sun",
    noVariants: true,
  },
  {
    id: "safari-egg",
    name: "Safari Egg",
    aliases: ["safari egg", "ovo safari"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.8,
    frUsd: 0.35,
    glyph: "sand",
    noVariants: true,
  },
  {
    id: "farm-egg",
    name: "Farm Egg",
    aliases: ["farm egg", "ovo farm"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.3,
    frUsd: 0.12,
    glyph: "moss",
    noVariants: true,
  },
  {
    id: "jungle-egg",
    name: "Jungle Egg",
    aliases: ["jungle egg", "ovo jungle"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.5,
    frUsd: 0.22,
    glyph: "forest",
    noVariants: true,
  },
  {
    id: "ocean-egg",
    name: "Ocean Egg",
    aliases: ["ocean egg", "ovo oceano"],
    cat: "egg",
    tier: "D",
    liq: "trash",
    demand: 1,
    frPts: 0.4,
    frUsd: 0.18,
    glyph: "ocean",
    noVariants: true,
  },
  {
    id: "aussie-egg",
    name: "Aussie Egg",
    aliases: ["aussie egg", "ovo aussie"],
    cat: "egg",
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 3,
    frUsd: 1.5,
    glyph: "copper",
    noVariants: true,
  },
  {
    id: "halloween-black-egg",
    name: "Halloween Black Egg",
    aliases: ["black egg", "ovo halloween", "ovo preto"],
    cat: "egg",
    tier: "C",
    liq: "medium",
    demand: 2,
    frPts: 2,
    frUsd: 1,
    glyph: "void",
    noVariants: true,
  },
  {
    id: "christmas-egg",
    name: "Christmas Egg",
    aliases: ["christmas egg", "ovo natal"],
    cat: "egg",
    tier: "D",
    liq: "low",
    demand: 1,
    frPts: 1,
    frUsd: 0.45,
    glyph: "blood",
    noVariants: true,
  },
];

export const PETS: Pet[] = SEEDS.map(expand);

export const PET_BY_ID: Record<string, Pet> = Object.fromEntries(
  PETS.map((pet) => [pet.id, pet]),
);

export const FEATURED_PETS = PETS.filter((pet) => pet.featured);

export function getPet(id: string) {
  return PET_BY_ID[id];
}

export function searchPets(query: string, limit = 12): Pet[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return [...PETS]
      .sort((a, b) => {
        const tier = a.tier.localeCompare(b.tier);
        if (tier !== 0) return tier;
        return b.values.fr.points - a.values.fr.points;
      })
      .slice(0, limit);
  }
  const scored = PETS.map((pet) => {
    const name = pet.name.toLowerCase();
    const aliasHit = pet.aliases.some((alias) => alias.toLowerCase().includes(q));
    let score = 0;
    if (name === q) score = 100;
    else if (name.startsWith(q)) score = 80;
    else if (name.includes(q)) score = 60;
    else if (pet.aliases.some((alias) => alias.toLowerCase() === q)) score = 75;
    else if (aliasHit) score = 50;
    if (score > 0 && pet.liquidity === "high") score += 4;
    if (score > 0 && pet.featured) score += 2;
    return { pet, score };
  })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score || b.pet.values.fr.points - a.pet.values.fr.points);
  return scored.slice(0, limit).map((row) => row.pet);
}

export function variantsFor(pet: Pet): Variant[] {
  if (!pet.hasVariants) return ["regular"];
  return ["regular", "fly", "ride", "fr", "nfr", "mfr"];
}
