/**
 * MAPA NOME -> ID gerado automaticamente a partir do catálogo
 * (src/lib/pets/catalog.ts): nome + alcunhas de todos os pets.
 *
 * NÃO EDITAR À MÃO — regenerar com:
 *   node --import ./scripts/test-register.mjs --experimental-strip-types scripts/gen-pet-names.mjs
 */
export const NAME_TO_ID = {
  "bat dragon": "bat-dragon",
  "bat": "bat-dragon",
  "morcego": "bat-dragon",
  "dragão morcego": "bat-dragon",
  "bat drag": "bat-dragon",
  "shadow dragon": "shadow-dragon",
  "shadow": "shadow-dragon",
  "sombra": "shadow-dragon",
  "dragão sombra": "shadow-dragon",
  "sombra drag": "shadow-dragon",
  "giraffe": "giraffe",
  "girafa": "giraffe",
  "gira": "giraffe",
  "frost dragon": "frost-dragon",
  "frost": "frost-dragon",
  "gelo": "frost-dragon",
  "dragão de gelo": "frost-dragon",
  "frost drag": "frost-dragon",
  "owl": "owl",
  "coruja": "owl",
  "parrot": "parrot",
  "papagaio": "parrot",
  "crow": "crow",
  "corvo": "crow",
  "african wild dog": "african-wild-dog",
  "awd": "african-wild-dog",
  "wild dog": "african-wild-dog",
  "cão selvagem": "african-wild-dog",
  "balloon unicorn": "balloon-unicorn",
  "balloon": "balloon-unicorn",
  "unicórnio balão": "balloon-unicorn",
  "balloon uni": "balloon-unicorn",
  "giant panda": "giant-panda",
  "panda gigante": "giant-panda",
  "evil unicorn": "evil-unicorn",
  "evil uni": "evil-unicorn",
  "unicórnio evil": "evil-unicorn",
  "evil": "evil-unicorn",
  "arctic reindeer": "arctic-reindeer",
  "arctic": "arctic-reindeer",
  "rena": "arctic-reindeer",
  "reindeer": "arctic-reindeer",
  "rena ártica": "arctic-reindeer",
  "turtle": "turtle",
  "tartaruga": "turtle",
  "kangaroo": "kangaroo",
  "canguru": "kangaroo",
  "kanga": "kangaroo",
  "albino monkey": "albino-monkey",
  "albino": "albino-monkey",
  "macaco albino": "albino-monkey",
  "hedgehog": "hedgehog",
  "ouriço": "hedgehog",
  "flamingo": "flamingo",
  "diamond butterfly": "diamond-butterfly",
  "borboleta diamante": "diamond-butterfly",
  "diamond ladybug": "diamond-ladybug",
  "ladybug diamante": "diamond-ladybug",
  "lion": "lion",
  "leão": "lion",
  "dalmatian": "dalmatian",
  "dálmata": "dalmatian",
  "queen bee": "queen-bee",
  "abelha rainha": "queen-bee",
  "hawk": "hawk",
  "falcão": "hawk",
  "vampire dragon": "vampire-dragon",
  "vampire": "vampire-dragon",
  "vampiro": "vampire-dragon",
  "dragão vampiro": "vampire-dragon",
  "lavender dragon": "lavender-dragon",
  "lavender": "lavender-dragon",
  "lavanda": "lavender-dragon",
  "ghost dragon": "ghost-dragon",
  "ghost": "ghost-dragon",
  "fantasma": "ghost-dragon",
  "dragão fantasma": "ghost-dragon",
  "ninja monkey": "ninja-monkey",
  "ninja": "ninja-monkey",
  "macaco ninja": "ninja-monkey",
  "skele-rex": "skele-rex",
  "skelerex": "skele-rex",
  "skele": "skele-rex",
  "esqueleto": "skele-rex",
  "king bee": "king-bee",
  "abelha rei": "king-bee",
  "phoenix": "phoenix",
  "fénix": "phoenix",
  "fenix": "phoenix",
  "t-rex": "t-rex",
  "trex": "t-rex",
  "t rex": "t-rex",
  "tiranossauro": "t-rex",
  "golden penguin": "golden-penguin",
  "pinguim dourado": "golden-penguin",
  "dodo": "dodo",
  "dragon": "dragon",
  "dragão": "dragon",
  "dragao": "dragon",
  "legendary dragon": "dragon",
  "frost fury": "frost-fury",
  "fury": "frost-fury",
  "octopus": "octopus",
  "polvo": "octopus",
  "unicorn": "unicorn",
  "unicórnio": "unicorn",
  "unicornio": "unicorn",
  "uni": "unicorn",
  "griffin": "griffin",
  "grifo": "griffin",
  "shark": "shark",
  "tubarão": "shark",
  "tubarao": "shark",
  "kitsune": "kitsune",
  "cobra": "cobra",
  "elephant": "elephant",
  "elefante": "elephant",
  "hyena": "hyena",
  "hiena": "hyena",
  "cerberus": "cerberus",
  "cérbero": "cerberus",
  "peacock": "peacock",
  "pavão": "peacock",
  "pavao": "peacock",
  "capybara": "capybara",
  "capivara": "capybara",
  "axolotl": "axolotl",
  "axolote": "axolotl",
  "snow owl": "snow-owl",
  "coruja da neve": "snow-owl",
  "zombie buffalo": "zombie-buffalo",
  "búfalo zombie": "zombie-buffalo",
  "brown bear": "brown-bear",
  "urso": "brown-bear",
  "polar bear": "polar-bear",
  "urso polar": "polar-bear",
  "swan": "swan",
  "cisne": "swan",
  "fennec fox": "fennec-fox",
  "fennec": "fennec-fox",
  "raposa fennec": "fennec-fox",
  "shiba inu": "shiba-inu",
  "shiba": "shiba-inu",
  "husky": "husky",
  "crocodile": "crocodile",
  "crocodilo": "crocodile",
  "red panda": "red-panda",
  "panda vermelho": "red-panda",
  "koala": "koala",
  "panda": "panda",
  "sloth": "sloth",
  "preguiça": "sloth",
  "preguica": "sloth",
  "platypus": "platypus",
  "ornitorrinco": "platypus",
  "narwhal": "narwhal",
  "narval": "narwhal",
  "dolphin": "dolphin",
  "golfinho": "dolphin",
  "black panther": "black-panther",
  "pantera": "black-panther",
  "cow": "cow",
  "vaca": "cow",
  "monkey": "monkey",
  "macaco": "monkey",
  "pig": "pig",
  "porco": "pig",
  "silly duck": "silly-duck",
  "pato": "silly-duck",
  "snowman": "snowman",
  "boneco de neve": "snowman",
  "ginger cat": "ginger-cat",
  "gato gengibre": "ginger-cat",
  "squid": "squid",
  "lula": "squid",
  "chicken": "chicken",
  "galinha": "chicken",
  "cat": "cat",
  "gato": "cat",
  "dog": "dog",
  "cão": "dog",
  "cao": "dog",
  "buffalo": "buffalo",
  "búfalo": "buffalo",
  "bufalo": "buffalo",
  "bandicoot": "bandicoot",
  "robin": "robin",
  "pisco": "robin",
  "ground sloth": "ground-sloth",
  "preguiça terrestre": "ground-sloth",
  "minion chick": "minion-chick",
  "minion": "minion-chick",
  "chick": "minion-chick",
  "pintainho": "minion-chick",
  "metal ox": "metal-ox",
  "boi metal": "metal-ox",
  "ox metal": "metal-ox",
  "ox": "ox",
  "boi": "ox",
  "crab": "crab",
  "caranguejo": "crab",
  "stingray": "stingray",
  "raia": "stingray",
  "sugar glider": "sugar-glider",
  "glider": "sugar-glider",
  "petauro": "sugar-glider",
  "esquilo voador": "sugar-glider",
  "tree kangaroo": "tree-kangaroo",
  "canguru da arvore": "tree-kangaroo",
  "canguru arvore": "tree-kangaroo",
  "albatross": "albatross",
  "albatroz": "albatross",
  "galah": "galah",
  "catatua": "galah",
  "abyssinian cat": "abyssinian-cat",
  "abyssinian": "abyssinian-cat",
  "gato abissinio": "abyssinian-cat",
  "sandbox turtle": "sandbox-turtle",
  "tartaruga sandbox": "sandbox-turtle",
  "tweetheart": "tweetheart",
  "cheerful otter": "cheerful-otter",
  "lontra": "cheerful-otter",
  "maneki-neko": "maneki-neko",
  "maneki neko": "maneki-neko",
  "maneki": "maneki-neko",
  "gato sorte": "maneki-neko",
  "zombie wolf": "zombie-wolf",
  "lobo zombie": "zombie-wolf",
  "dragao vampiro": "vampire-dragon",
  "undead elk": "undead-elk",
  "alce undead": "undead-elk",
  "chimera": "chimera",
  "quimera": "chimera",
  "lunar ox": "lunar-ox",
  "boi lunar": "lunar-ox",
  "ride potion": "ride-potion",
  "ride": "ride-potion",
  "rp": "ride-potion",
  "poção ride": "ride-potion",
  "pocao ride": "ride-potion",
  "ride pot": "ride-potion",
  "fly potion": "fly-potion",
  "fly": "fly-potion",
  "fp": "fly-potion",
  "poção fly": "fly-potion",
  "pocao fly": "fly-potion",
  "fly pot": "fly-potion",
  "age-up potion": "age-up-potion",
  "age up": "age-up-potion",
  "aup": "age-up-potion",
  "poção idade": "age-up-potion",
  "cracked egg": "cracked-egg",
  "ovo rachado": "cracked-egg",
  "royal egg": "royal-egg",
  "ovo royal": "royal-egg",
  "ovo atual": "royal-egg",
  "current egg": "royal-egg",
  "safari egg": "safari-egg",
  "ovo safari": "safari-egg",
  "farm egg": "farm-egg",
  "ovo farm": "farm-egg",
  "jungle egg": "jungle-egg",
  "ovo jungle": "jungle-egg",
  "ocean egg": "ocean-egg",
  "ovo oceano": "ocean-egg",
  "aussie egg": "aussie-egg",
  "ovo aussie": "aussie-egg",
  "halloween black egg": "halloween-black-egg",
  "black egg": "halloween-black-egg",
  "ovo halloween": "halloween-black-egg",
  "ovo preto": "halloween-black-egg",
  "christmas egg": "christmas-egg",
  "ovo natal": "christmas-egg",
};
